### ISSUE TITLE
ゲーム題材の決定

### ISSUE THREAD

**Issue by onose004** [maselab/hoppin#1]
卒業式までを目処に以下のことを決めたい。
- [x] 参考になる題材の決定
- [x] プロコンへの落とし込み
  - 2人対戦の場合どうするか
  - ホワイトボードを使って、ゲームモデルを説明できるように
- [x] 文書への落とし込み

**Comment by onose004** [comment]
## 大まかなルール by 橋口
- 1マス以上を通過点により囲む
- 囲めたら，自分の色のマスが得点になる
- 得点になったマスは，消失する（blank）
- 自陣の１マス外側を囲みマスに貢献できる
- 他のプレイヤーの色を通過すると，上書きされる
- ターン制

**Comment by onose004** [comment]
## クラス分割
- Player
  - 児玉
- GameManager
  - 橋口，林
  - Class FieldState
  - Class GameState
  - _中断！_
- GameGraphic
  - 小野瀬

**Comment by MthBridge** [comment]
記述方法はテキトー,　フィールド表現はint配列にしました．
4人のPlayerの通し番号は付けるべき？
まだ未完成やけど．

```

Class GameManager
{
    GameState;
    PlayerList;
    Graphic;
    Judgement;
}

interface Judgement
{
    judge(PlayerMove,GameState)
    //プレイヤーの移動判定，スコア判定，GameStateの修正を行う関数の提供．
}

Class GameState
{
    int gameBoard[8][8];
    int playerPosition[8][8];  // blank : 0 player1 : 1 player2 : 2......
    int playerScore[4];
    int? outFrame;  // 外枠の位置．
}

Enum PlayerMove
{ up,down,left,right; }

interface Graphic
{
    ChangeField(FieldState);
    MovePlayer(playerMove//4人分);
    ChangeOutFrame(outFrame);
    ChangeScore(playerScore);
    //グラフィックに変動があるときに呼び出す関数の提供
}

abstract Player
{
    String playerName;
    abstract PlayerMove Move();
}
```

**Comment by chayash1** [comment]
### 消去判定アルゴリズム（案）
- 一人が移動するたびに判定
- ボードの各マスを全探索し、囲まれているところを見つける
- 囲まれているところ　＝　どの壁から辿ろうとしても、たどり着けない箇所(離れ小島の空マス)

### アルゴリズム (プレーヤーAの移動後の消去判定)
- プレーヤーA色以外のマスを一時的に空マスとみなす
- 座標（i,j）を見る　番号未割り振りかつ空マスであれば番号xを割り振る
- 座標（i,j）から4方向の座標をそれぞれ見て、番号未割り振りかつ空マスであれば番号ｘを割り振る
- ↑を再帰処理、これを全マスについて行う　再帰がリセットされるたびに割り振り番号を変更するx -> x+1
- 割り振り後、自分の色以外の壁、の隣に空マスがあれば、その空マスに割り振られている番号の領域は離れ小島ではないので無効
- これを繰り返し、無効ではない割り振り番号が見つかれば囲み箇所があることになる

### 案その2
- 自色以外のマスを空マスとみなす
- 他色壁に隣接する空マスを見つける。
- その空マスを使った囲み領域は存在しないので、再帰的にその領域全体を割り出して、除外する。
- これを全他色壁に対して行い最後までのこる空マスがあれば、囲みあり。

**Comment by onose004** [comment]
@MthBridge @chayash1 後の話になりそうだけど，議論がまとまったら Wiki にまとめていきましょ．

**Comment by chayash1** [comment]
ルール
・盤面８＊８
・4人対戦　ターン制(n*4)　もっともスコアが高い人が勝ち
・自分のターンに1マスずつ移動する→盤面に色を塗る→箱を取る

・盤面にはアイテムと！箱がランダムに設置される
　アイテム
　 ー矢印：取ると、向いている方向のマスが全て自分の色になる
　 ー靴　：取ると、一定回数１ターンに複数回（２回？）移動できる
    ーその他：アイデアがあれば

・盤面に色を塗る方法
　ー自分の色で空マスや相手の色を囲む
　ー１マス移動のとき、移動先のマスが自分の色になる

・ポイントを稼ぐ方法
　ー盤面にランダムに設置される！箱を取る
　ー囲みによる塗りつぶしを成立させる（？）

**Comment by MthBridge** [comment]
Judgementクラスについて．
無くしてManagerクラスのメソッドにしたい．

**Comment by MthBridge** [comment]
Judgementクラスがプレイヤーから見えてるので使うと処理楽になっちゃいます．ですんで，internalかクラス内のクラスにするかして，後々見えないように工夫します．今はこのまま開発しませう

**Comment by onose004** [comment]
@MthBridge 1日の終わりにでもちょくちょくコミットしてもらえると🙆

**Comment by chayash1** [comment]
判定の順番(あいまいさを回避)
・プレイヤーの移動
↓
・囲み判定
↓
・アイテム取得判定
!箱を壊すと同時に囲みが成立すると囲みも含んだ得点が入る
移動先に一方向塗りつぶしの矢印があり、それを踏んだことにより囲みが生じても囲みとはみなさない
（あくまでも自分の足で囲む）

**Comment by chayash1** [comment]
備忘録
FieldObject : {BLANK,PLAYER1,PLAYER2,PLAYER3,PLAYER4,SHOES,ARROW }
ARROWは4方向あるなら４つ必要なのでは？
fieldFloorColor : {BLANK,PLAYER1,PLAYER2,PLAYER3,PLAYER4}

private void MovePlayer(){
//メイン処理
//・currentPlayerMoveとFieldObjectを参照し移動先を確認
//(if)移動先にプレイヤーがいる→無効な移動と判断して動かない
//(if)移動先が壁→無効な移動と判断して動かない
//(if)移動先にアイテムがある→ Repaint , GetItemsを呼び出してアイテム処理
//(if)移動先が普通のマス → Repaint 
//(if)else 例外

//GenerateItemsでアイテム生成
//例外チェック(FieldObjectに各プレーヤーが1人ずついるか)

}
private void GetItems{
//アイテムの取得
//if(靴)靴取得フラグをたてる
//if(矢印)矢印方向の色を塗りつぶす
//if(!箱) AddScoreを呼び出す
//else 例外

//取得したアイテムをFieldObjectsから削除
}
private void GenerateItems(){
//アイテムの生成
//生成条件を設ける
//・一定確率で生成(x%)
//・盤面にn個アイテムがあると生成しない
//・生成されたアイテムには最低m個！箱がある
}
private void Repaint(){
//移動先マスの塗り替えを行う
//囲み領域の探索 SearchClosedSpace を呼ぶ
}
private Boolean SearchClosedSpace(){
//囲み空間を探索する関数
//囲み空間を見つけたら塗りつぶす
}
private void AddScore(){
//スコア加算
//スコア変更と盤面の塗り替えも行う
}

**Comment by nose004** [comment]
一応閉じます

**Comment by onose004** [comment]
長くなってるので閉じます。
