### ISSUE TITLE
開発環境の決定

### ISSUE THREAD

**Issue by onose004** [maselab/hoppin#2]
確認しなきゃいけないこと
- [x] AI のインタフェースに用いる言語
- [x] 参加者向けの設計マニュアルの作成方法

**Comment by MthBridge** [comment]
言語は特に決めとかないといかん．
広島市大の人に伝えるから今週中を目処に

**Comment by onose004** [comment]
@MthBridge OK とりあえず，金曜日の 10:00〜 のミーティングで決定しましょう。

**Comment by onose004** [comment]
> 参加者向けの設計マニュアルの作成方法

について
[Doxygen](http://www.doxygen.jp/install.html) あたりを使うと良さそう。
ソースコード内のコメントの書き方を要確認。

**Comment by onose004** [comment]
ソースコードからドキュメントを自動生成してくれるツールを使うと，ソースコードに適切なコメントが付けて俯瞰しやすいし，作成の手間を省ける。

**Comment by onose004** [comment]
C# で決定！
理由: 実利主義
